version: 1.2
workflows:
 - name: ODHL-AR-Pipeline
   subclass: WDL
   primaryDescriptorPath: /workflows/arAnalysis.wdl
   testParameterFiles:
    - /tests/inputs/empty.json
 - name: ODHL-AR-Formatter
   subclass: WDL
   primaryDescriptorPath: /workflows/arFormatter.wdl
   testParameterFiles:
    - /tests/inputs/empty.json